#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_cut()
{
    local cur prev words cword options cmds
    _init_completion
    cur=$(printf '%q' "${cur,,}")
    cmds=( ${words[@]::cword} ) 
    options=( '-b' '--bytes=' '-c' '--characters=' '-d' \
        '--delimiter=' '-f' '--fields=' '--complement' '-s' \
        '--only-delimited' '--output-delimiter=' '--help' '--version' )
    options=$(_compliment cmds[@] options[@])
    COMPREPLY=( $( compgen -f -W '$options' -- $cur ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

complete -o default -F _cut cut cut.exe

