#!/usr/bin/env sh

# TODO: pass completion off to other function for the associated command
# TODO: remove duplicate and mutual exclusive options

_cygcheck_list()
{
    cygcheck -c -d | sed -e '1,2d' -e 's/ .*//g'
}

_cygcheck()
{
    COMPREPLY=()

    local cur=$(printf '%q' "${COMP_WORDS[COMP_CWORD]}")
    local options=''

    if [[ $COMP_CWORD -eq 1 ]]; then
        options='-c --check-setup -s --sysinfo -k --keycheck -f --find-package
        -l --list-package -p --package-query -h --help
        --delete-orphaned-installation-keys --enable-unique-object-names
        --disable-unique-object-names --show-unique-object-names -v --verbose'
    fi

    case $(printf '%q' "${COMP_WORDS[1]}") in

        -h)
            ;&
        -v)
            ;&
        --help)
            ;&
        --verbose)
            if [[ $COMP_CWORD -eq 2 ]]; then
                options='-v -h --verbose --help'
            fi
            ;;

        -c)
            ;&
        --check-setup)
            if [[ $COMP_CWORD -eq 2 ]]; then
                local IFS=$'\n'
                if [[ $cur != -* ]]; then
                    options=$(_cygcheck_list)
                fi
                options+=$'\n''-d' 
                options+=$'\n''--dump-only'
            elif [[ $COMP_CWORD -eq 3 && ( ${COMP_WORDS[2]} == -d || ${COMP_WORDS[2]} == --dump-only ) ]]; then
                local IFS=$'\n'
                options=$(_cygcheck_list)
            fi
            ;;

        -s)
            ;&
        --sysinfo)
            if [[ $COMP_CWORD -ge 2 && $COMP_CWORD -le 4 ]]; then
                options='-r --registry -v --verbose -h --help'
            fi
            ;;

        -l)
            ;&
        --list-package)
            local IFS=$'\n'
            options=$(_cygcheck_list)
            ;;

        -f)
            ;&
        -p)
            ;&
        --find-package)
            ;&
        --package-query)
            ;&
        --enable-unique-object-names)
            ;&
        --disable-unique-object-names)
            ;&
        --show-unique-object-names)
            ;;

    esac

    if [ -n "$options" -a -z "$COMPREPLY" ]; then
        COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    fi

    return 0
}

complete -o default -F _cygcheck cygcheck cygcheck.exe

