#!/usr/bin/env sh

# TODO: pass completion off to other function for the associated command
# TODO: remove duplicate and mutual exclusive options

_cygdrop_group()
{
    local options=$(wmic group get name | sed -e '1d' -e 's/\r//' -e 's/ \+$//' -e '/\$$/ d' -e '/^$/ d')

    # escape bash tokenizer strings and separate with newlines
    local IFS=$'\n'
    options=$(printf '%q\n' $options)

    # escape bash completion word breaks that aren't otherwise escaped by "printf '%q'"
    options=`echo "$options" | sed 's/[:=]/\\\&/g'`

    # make lowercase for convenience
    options=${options,,}

    echo "$options"
}

_cygdrop()
{
    COMPREPLY=()

    local cur=$(printf '%q' "${COMP_WORDS[COMP_CWORD]}")
    local options=''

    case $(printf '%q' "${COMP_WORDS[COMP_CWORD-1]}") in

        -g)
            ;&
        -G)
            ;&
        -r)
            local IFS=$'\n'
            options=$(_cygdrop_group)
            ;;

        -p)
            ;&
        -P)
            options='SeAssignPrimaryTokenPrivilege SeAuditPrivilege
            SeBackupPrivilege SeChangeNotifyPrivilege SeCreateGlobalPrivilege
            SeCreatePagefilePrivilege SeCreatePermanentPrivilege
            SeCreateSymbolicLinkPrivilege SeCreateTokenPrivilege
            SeDebugPrivilege SeEnableDelegationPrivilege SeImpersonatePrivilege
            SeIncreaseBasePriorityPrivilege SeIncreaseQuotaPrivilege
            SeIncreaseWorkingSetPrivilege SeLoadDriverPrivilege
            SeLockMemoryPrivilege SeMachineAccountPrivilege
            SeManageVolumePrivilege SeProfileSingleProcessPrivilege
            SeRelabelPrivilege SeRemoteShutdownPrivilege SeRestorePrivilege
            SeSecurityPrivilege SeShutdownPrivilege SeSyncAgentPrivilege
            SeSystemEnvironmentPrivilege SeSystemProfilePrivilege
            SeSystemtimePrivilege SeTakeOwnershipPrivilege SeTcbPrivilege
            SeTimeZonePrivilege SeTrustedCredManAccessPrivilege
            SeUndockPrivilege SeUnsolicitedInputPrivilege'
            ;;

        *)
            options='-l -d -g -G -r -m --help -h --usage --version --license -v
            -p -P'
            ;;

    esac

    if [ -n "$options" -a -z "$COMPREPLY" ]; then
        COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    fi

    return 0
}

complete -o default -F _cygdrop cygdrop cygdrop.exe

