#!/usr/bin/env sh

# TODO: pass completion off to other function for the associated command
# TODO: remove duplicate and mutual exclusive options

_cygdrop_group()
{
    local options IFS
    IFS=$'\n'
    options=$(wmic group get name | sed -e '1d' -e 's/\r//' -e 's/ \+$//' -e '/\$$/ d' -e '/^$/ d')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\\&/g' -e "/''/d"
}

_cygdrop()
{
    local cur prev words cword options IFS
    _init_completion
    cur=$(printf '%q' "$cur")

    case $prev in

        -g|-G|-r)
            IFS=$'\n'
            options=$(_cygdrop_group)
            ;;

        -p|-P)
            options='SeAssignPrimaryTokenPrivilege SeAuditPrivilege
            SeBackupPrivilege SeChangeNotifyPrivilege SeCreateGlobalPrivilege
            SeCreatePagefilePrivilege SeCreatePermanentPrivilege
            SeCreateSymbolicLinkPrivilege SeCreateTokenPrivilege
            SeDebugPrivilege SeEnableDelegationPrivilege SeImpersonatePrivilege
            SeIncreaseBasePriorityPrivilege SeIncreaseQuotaPrivilege
            SeIncreaseWorkingSetPrivilege SeLoadDriverPrivilege
            SeLockMemoryPrivilege SeMachineAccountPrivilege
            SeManageVolumePrivilege SeProfileSingleProcessPrivilege
            SeRelabelPrivilege SeRemoteShutdownPrivilege SeRestorePrivilege
            SeSecurityPrivilege SeShutdownPrivilege SeSyncAgentPrivilege
            SeSystemEnvironmentPrivilege SeSystemProfilePrivilege
            SeSystemtimePrivilege SeTakeOwnershipPrivilege SeTcbPrivilege
            SeTimeZonePrivilege SeTrustedCredManAccessPrivilege
            SeUndockPrivilege SeUnsolicitedInputPrivilege'
            ;;

        *)
            options=('-l' '-d' '-g' '-G' '-r' '-m' '--help' '-h' '--usage'
            '--version' '--license' '-v' '-p' '-P')
            options=$(_compliment words[@]::cword options[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _cygdrop cygdrop cygdrop.exe

