#!/usr/bin/env sh

_cygpath()
{
    local cur prev words cword options
    _init_completion
    cur=$(printf '%q' "$cur")

    case $prev in

        -f|--file)
            return
            ;;

        -t|--type)
            options='dos mixed unix windows'
            ;;

        -C|--codepage)
            # TODO: list all available code pages
            options='ansi oem utf8'
            ;;

        --F|--folder)
            # TODO: list special folder ids
            options=''
            ;;

        -c|--close)
            # TODO: list handles
            options=''
            ;;

        *)
            # TODO: cull duplicate and mutually exclusive options
            options='-d -m -M -u -w -t -a -l -p -s -C -A -D -H -O -P -S -W -F
            --dos --mixed --mode --unix --windows --type --absolute --long-name
            --path --short-name --codepage --allusers --desktop --homeroot
            --mydocs --smprograms --sysdir --windir --folder --help -f --file
            -o --option -c --close -i --ignore -h -V --version'
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _cygpath cygpath cygpath.exe

