#!/usr/bin/env sh

_cygpath()
{
    COMPREPLY=()
    local cur=$(printf '%q' "${COMP_WORDS[COMP_CWORD]}")
    local options=''

    case ${COMP_WORDS[COMP_CWORD-1]} in

        -t)
            ;&
        --type)
            options='dos mixed unix windows'
            ;;

        -C)
            ;&
        --codepage)
            # TODO: list code pages
            options='ansi oem utf8'
            ;;

        --F)
            ;&
        --folder)
            # TODO: list special folder ids
            options=''
            ;;

        -f)
            ;&
        --file)
            options=''
            ;;

        -c)
            ;&
        --close)
            options=''
            ;;

        *)
            # TODO: cull duplicate and mutually exclusive options
            options='-d -m -M -u -w -t -a -l -p -s -C -A -D -H -O -P -S -W -F
            --dos --mixed --mode --unix --windows --type --absolute --long-name
            --path --short-name --codepage --allusers --desktop --homeroot
            --mydocs --smprograms --sysdir --windir --folder --help -f --file
            -o --option -c --close -i --ignore -h -V --version'
            ;;

    esac

    if [ -n "$options" -a -z "$COMPREPLY" ]; then
        COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    fi

    return 0
}

complete -o default -F _cygpath cygpath cygpath.exe

