#!/usr/bin/env sh

# TODO: completion for the program specified by the --path / -p argument?

_cygrunsrv_list_users()
{
    local options IFS
    IFS=$'\n'
    options=$(wmic useraccount get name | sed -e '1d' -e 's/\r//' -e 's/ \+$//' -e '/\$$/ d' -e '/^$/ d')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_cygrunsrv_list_svcs()
{
    local options IFS
    IFS=$'\n'
    options=$(cygrunsrv --list)
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_cygrunsrv()
{
    local cur prev words cword options IFS
    _init_completion
    cur=$(printf '%q' "$cur")

    if [[ $cword -eq 1 ]]; then
        options='-I --install -R --remove -S --start -E --stop -Q --query -L
        --list -h --help -v --version'
        COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
        return
    fi

    case ${words[1]} in

        -R|-S|-E|-Q|-L|--remove|--start|--stop|--query|--list)
            if [[ $cword -eq 2 ]]; then
                IFS=$'\n'
                options=$(_cygrunsrv_list_svcs)
            fi
            ;;

        -I|--install)
            if [[ $cword -eq 2 ]]; then
                options=''
            elif [[ $cword -eq 3 ]]; then
                options='-p --path'
            elif [[ $cword -eq 4 ]]; then
                options=''
            else

                case $prev in

                    -P|--crs-path|-a|--args|-c|--chdir|-e|--env|-d|--disp|-f|--desc|-w|--passwd|-0|--stdin|-1|--stdout|-2|--stderr|-x|--pidfile)
                        return
                        ;;

                    -t|--type)
                        options='auto manual'
                        ;;

                    -u|--user)
                        IFS=$'\n'
                        options=$(_cygrunsrv_list_users)
                        ;;

                    -s|--termsig|-z|--shutsig)
                        _signals -
                        ;;

                    -y|--dep)
                        IFS=$'\n'
                        options=$(_cygrunsrv_list_svcs)
                        ;;

                    *)
                        # TODO: cull mutually exclusive options
                        local cmds=( ${words[@]::cword} ) 
                        options=('-P' '--crs-path' '-a' '--args' '-c' '--chdir'
                        '-e' '--env' '-d' '--disp' '-f' '--desc' '-t' '--type'
                        '-u' '--user' '-w' '--passwd' '-s' '--termsig' '-z'
                        '--shutsig' '-y' '--dep' '-0' '--stdin' '-1' '--stdout'
                        '-2' '--stderr' '-x' '--pidfile' '-n' '--neverexits'
                        '-O' '--preshutdown' '-o' '--shutdown' '-i'
                        '--interactive' '-j' '--nohide')
                        options=$(_complement cmds[@] options[@])
                        ;;

                esac

            fi
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _cygrunsrv cygrunsrv cygrunsrv.exe

