#!/usr/bin/env sh

# TODO: pass completion off to other function for the associated command
# TODO: remove mutually exclusive options

_cygstart()
{
    local cur prev words cword options cmds
    _init_completion

    cur=$(printf '%q' "$cur")
    cmds=( ${words[@]::cword} ) 

    options=('--help' '-?' '--usage' '--version' '--license' '--reference' '-v'
    '--verbose' '-w' '-a' '--action\=open' '--action\=explore' '--action\=edit'
    '--action\=find' '--action\=print' '-o' '--open' '-x' '--explore' '-e'
    '--edit' '-f' '--find' '-p' '--print' '--hide' '--maximize' '--minimize'
    '--restore' '--show' '--shownormal' '--showmaximized' '--showminimized'
    '--showminnoactive' '--showna' '--shownoactivate' '--wait' '-d'
    '--directory=')

    options=$(_complement cmds[@] options[@])

    COMPREPLY=( $(compgen -W '$options' -- $cur ) )
    [[ $COMPREPLY == *: ]] && compopt -o nospace
}

complete -o default -F _cygstart cygstart cygstart.exe

