#!/usr/bin/env sh

# TODO: pass completion off to other function for the associated command
# TODO: remove duplicate and mutual exclusive options

_cygstart()
{
    local cur prev words cword options
    _init_completion
    cur=$(printf '%q' "$cur")

    options='--help -? --usage --version --license --reference -v
    --verbose -w -a --action\=open --action\=explore --action\=edit
    --action\=find --action\=print -o --open -x --explore -e --edit -f --find
    -p --print --hide --maximize --minimize --restore --show --shownormal
    --showmaximized --showminimized --showminnoactive --showna --shownoactivate
    --wait -d --directory='

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _cygstart cygstart cygstart.exe

