#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_diff()
{
    local cur prev words cword options cmds
    _init_completion
    cur=$(printf '%q' "${cur,,}")
    cmds=( ${words[@]::cword} )
    options=( '--normal' '-q' '--brief' '-s' \
        '--report-identical-files' '-c' '-C' '--context' '--context=' '-u' '-U' \
        '--unified' '--unified=' '-e' '--ed' '-n' '--rcs' '-y' '--side-by-side' \
        '-W' '--width=' '--left-column' '--suppress-common-lines' '-p' \
        '--show-c-function' '-F' '--show-function-line=' '--label' '-t' \
        '--expand-tabs' '-T' '--initial-tab' '--tabsize=' \
        '--suppress-blank-empty' '-l' '--paginate' '-r' '--recursive' '-N' \
        '--new-file' '--unidirectional-new-file' '--ignore-file-name-case' \
        '--no-ignore-file-name-case' '-x' '--exclude=' '-X' '--exclude-from=' \
        '-S' '--starting-file=' '--from-file=' '--to-file=' '-i' \
        '--ignore-case' '-E' '--ignore-tab-expansion' '-Z' \
        '--ignore-trailing-space' '-b' '--ignore-space-change' '-w' \
        '--ignore-all-space' '-B' '--ignore-blank-lines' '-I' \
        '--ignore-matching-lines=' '-a' '--text' '--strip-trailing-cr' '-D' \
        '--ifdef=' '--GTYPE-group-format=' '--line-format=' \
        '--LTYPE-line-format=' '-d' '--minimal' '--horizon-lines=' \
        '--speed-large-files' '--help' '-v' '--version')
    options=$(_compliment cmds[@] options[@])
    COMPREPLY=( $( compgen -f -W '$options' -- $cur ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

complete -o default -F _diff diff diff.exe

