#!/usr/bin/env sh

_driverquery_users()
{
    local IFS options
    IFS=$'\n'
    options=$(wmic useraccount get name 2> /dev/null | sed -e '1d' -e '$d' -e 's/\W*$//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_driverquery()
{
    local cur prev words cword options IFS
    _init_completion

    # Command-specific arguments
    case $prev in

        /p)
            return
            ;;

        /s)
            # TODO: list computer names without leading slashes
            return
            ;;

        /fo)
            options='table list csv'
            ;;

        /u)
            IFS=$'\n'
            options=$(_driverquery_users)
            ;;

        *)
            options=('/s' '/fo' '/nh' '/si' '/v')

            case ${words[$cword-2]} in

                /s)
                    options+=('/u')
                    ;;

                /u)
                    options+=('/p')
                    ;;
            esac

            local cmds=( ${words[@]::cword} ) 
            options=$(_complement words[@]::cword options[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '${options}' -- ${cur} ) )
}

complete -o default -F _driverquery driverquery driverquery.exe

