#!/usr/bin/env sh

_driverquery_users()
{
    local options IFS
    IFS=$'\n'
    local options=$(wmic useraccount get name | sed -e '1d' -e 's/\r//' -e 's/ \+$//' -e '/\$$/ d' -e '/^$/ d')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\\&/g' -e "/''/d"
}

_driverquery()
{
    local cur prev words cword options IFS option_list found
    _init_completion

    # Command-specific arguments
    case $prev in

        /s|/p)
            ;;

        /fo)
            options='table list csv'
            ;;

        /u)
            IFS=$'\n'
            options=$(_driverquery_users)
            ;;

        *)
            option_list=('/s' '/fo' '/nh' '/si' '/v')

            case ${words[$cword-2]} in

                /s)
                    option_list+=('/u')
                    ;;

                /u)
                    option_list+=('/p')
                    ;;
            esac

            for option in ${option_list[@]} ; do
                found=0

                for word in ${words[@]::$cword} ; do
                    if [[ $word == $option ]]; then
                        found=1 
                        break
                    fi
                done

                if [[ $found -eq 0 ]]; then
                    options+="$option "
                fi
            done
            ;;

    esac

    COMPREPLY=( $(compgen -W '${options}' -- ${cur} ) )
}

complete -o default -F _driverquery driverquery driverquery.exe

