#!/usr/bin/env sh

_dumpbin()
{
    local cur prev words cword options cmds
    _init_completion
    cur=$(printf '%q' "${cur,,}")

    if [[ $prev == '/?' ]]; then
        return
    fi

    options=('/all' '/archivemembers' '/clrheader' '/dependents' 
    '/directives' '/disasm\:bytes' '/disasm\:nobytes' '/errorreport\:none'
    '/errorreport\:prompt' '/errorreport\:queue' '/errorreport\:send'
    '/exports' '/fpo' '/headers' '/imports' '/linenumbers' '/linkermember'
    '/loadconfig' '/nologo' '/out\:' '/pdata' '/pdbpath' '/range\:'
    '/rawdata' '/rawdata\:none' '/relocations' '/section\:' '/summary'
    '/symbols' '/tls' '/unwindinfo' '/?' )

    cmds=( ${words[@]::cword} ) 
    options=$(_complement cmds[@] options[@])

    COMPREPLY=( $(compgen -W '$options' -- $cur ) )
    [[ $COMPREPLY == *: ]] && compopt -o nospace
}

complete -o default -F _dumpbin dumpbin dumpbin.exe

