#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_head()
{
    local cur prev words cword options cmds
    _init_completion
    cur=$(printf '%q' "${cur,,}")
    options=( '-c' '--bytes=' '-n' '--lines=' '-q' '--quiet' '--silent' '-v'
    '--verbose' '--help ' '--version')
    options=$(_complement cmds[@] options[@])
    COMPREPLY=( $( compgen -f -W '$options' -- $cur ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

complete -o default -F _head head

