#!/usr/bin/env sh

_ipconfig_interfaces()
{
    local options IFS
    IFS=$'\n'
    options=$(netsh interface show interface name= | sed -e '/^$/ d' -e 's/.\{47\}//' )
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_ipconfig()
{
    local cur prev words cword options IFS
    _init_completion

    cur=$(printf '%q' "${cur,,}")

    if [[ $cword -eq 1 ]] ; then
        COMPREPLY=( $( compgen -W '/all /renew /release /allcompartments /flushdns \
            /renew6 /release6 /displaydns /registerdns /showclassid \
            /setclassid /showclassid6 /setclassid6 /?' -- $cur ) )
        return
    fi

    if [[ $prev == '/?' ]]; then
        return
    fi

    # Command-specific arguments
    case ${words[1]} in

        /showclassid6|/setclassid6|/showclassid|/setclassid|/renew6|/release6|/renew|/release)
            IFS=$'\n' # interfaces are newline separated
            options=$(_ipconfig_interfaces)
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- $cur ) )
}

complete -o default -F _ipconfig ipconfig ipconfig.exe

