#!/usr/bin/env sh

_msbuild_end()
{
    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    [[ $COMPREPLY == *: ]] && compopt -o nospace
    [[ $COMPREPLY == *= ]] && compopt -o nospace
    [[ $COMPREPLY == *\; ]] && compopt -o nospace
}

_msbuild()
{
    local cur prev words cword options existing_options raw_cur
    _init_completion
    cur=$(printf '%q' "$cur")
    raw_cur=${words[cword]}

    # TODO: cull used options and remove mutually exclusive options

    case $raw_cur in

        /consoleloggerparameters\\:*)
            existing_options=$(echo "$raw_cur" | sed -e 's/[^:;]*$//')

            for new_option in 'performancesummary' 'summary' 'nosummary' \
                'errorsonly' 'warningsonly' 'noitemandpropertylist' \
                'showcommandline' 'showtimestamp' 'showeventid' 'forcenoalign' \
                'disableconsolecolor' 'verbosity\=quiet' 'verbosity\=minimal' \
                'verbosity\=normal' 'verbosity\=detailed' \
                'verbosity\=diagnostic' 'disablemplogging' 'enablemplogging';
            do
                options+=" ${existing_options}${new_option}\; "
            done

            _msbuild_end
            return
            ;;

        /fileloggerparameters\\:*)
            existing_options=$(echo "$raw_cur" | sed -e 's/[^:;]*$//')

            # TODO: fix logfile= so that it will stop and suggest files
            for new_option in 'logfile\=' 'append' 'encoding\=utf-8' \
                'encoding\=unicode' 'encoding\=ascii'; do
                options+=" ${existing_options}${new_option}\; "
            done

            _msbuild_end
            return
            ;;

        @*)
            # TODO: list files
            options='@'
            _msbuild_end
            return
            ;;

        /target\\:*)
            # TODO: list avilable targets from the given project file, if available in the command string or in the current directory
            options='/target\:'
            _msbuild_end
            return
            ;;

        *)
            options=('/target\:' '/property\:' '/maxcpucount\:' '/maxcpucount'
            '/toolsversion\:' '/verbosity\:quiet' '/verbosity\:minimal'
            '/verbosity\:normal' '/verbosity\:detailed'
            '/verbosity\:diagnostic' '/consoleloggerparameters\:'
            '/noconsolelogger' '/filelogger' '/fileloggerparameters\:'
            '/distributedlogger\:' '/distributedfilelogger' '/logger\:'
            '/validate' '/validate\:' '/ignoreprojectextensions\:'
            '/nodereuse\:true' '/nodereuse\:false' '/preprocess'
            '/preprocess\:' '/detailedsummary' '@' '/noautoresponse' '/nologo'
            '/version' '/help')
            options=$(_compliment words[@]::cword options[@])

            _msbuild_end
            return
            ;;

    esac
}

complete -o default -F _msbuild msbuild msbuild.exe MSBuild MSBuild.exe

