#!/usr/bin/env sh

_msiexec_pkgs()
{
    local options IFS
    IFS=$'\n'
    options=$( ( reg query 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'; reg query 'HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall' ) | sed -e 's/[^{]*//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\\&/g' -e "/''/d"
}

_msiexec_end()
{
    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

_msiexec()
{
    local cur prev words cword options IFS install_options repair_options restart_options display_options log_options
    _init_completion

    cur=$(printf '%q' "$cur")
    install_options='/package /i /a /j /ju /jm /uninstall /x /update'
    repair_options='/f /fp /fo /fe /fd /fc /fa /fu /fm /fs /fv' 
    restart_options='/norestart /promptrestart /forcerestart'
    display_options='/quiet /passive /q /qn /qb /qr /qf /help'
    log_options='/l /li /lw /le /la /lr /lu /lc /lm /lo /lp /lv /lx /l\+ /l\! /l\* /log'

    if [[ $cword -eq 1 ]]; then
        options="$install_options $repair_options"
        _msiexec_end
        return
    fi

    case $prev in
        /l|/li|/lw|/le|/la|/lr|/lu|/lc|/lm|/lo|/lp|/lv|/lx|/l\+|/l\!|/l\*|/log)
            return
            ;;
    esac

    case ${words[1]} in

        /a|/uninstall|/x|/update|/i|/package)
            if [[ $cword -gt 2 ]]; then
                options="$restart_options $display_options $log_options"
                _msiexec_end
                return
            fi
            ;;

        /j*)
            if [[ $cword -eq 2 ]]; then
                # TODO: suggest msi files?
                options=''
            else
                options="/t /g $restart_options $display_options $log_options"

                case ${words[cword-1]} in

                    /t)
                        # TODO: list transforms
                        options=''
                        ;;

                    /g)
                        # TODO: list language ids
                        options=''
                        ;;

                esac

            fi

            _msiexec_end
            return
            ;;

        /f*|/x|/uninstall)
            if [[ $cword -eq 2 ]]; then
                # TODO: suggest msi files?
                local IFS=$'\n'
                options=$(_msiexec_pkgs)
            else
                options="$restart_options $display_options $log_options"
            fi

            _msiexec_end
            return
            ;;

    esac
}

complete -o default -F _msiexec msiexec msiexec.exe

