#!/usr/bin/env sh

_mstsc_computer_names()
{
    local IFS options
    IFS=$'\n'
    local options=$(net view /all 2> /dev/null | sed -e '/^\\\\/!d' -e 's/ .*//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_mstsc()
{
    local cur prev words cword options cmds IFS
    _init_completion
    cur=$(printf '%q' "${cur,,}")

    case $prev in
        /w\\:*|/h\\:*|/edit)
            return
            ;;
    esac

    case $cur in

        /v\\:*)
            # TODO: remove leading slashes
            IFS=$'\n'
            options=$(printf '/v\\:%s\n' _mstsc_computer_names)
            ;;

        *)
            cmds=( ${words[@]::cword} ) 
            options=('/admin' '/f' '/fullscreen' '/w\:' '/h\:' '/public'
            '/plan' '/multimon' '/migrate' '/edit' '/v\:')
            options=$(_complement words[@]::cword options[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- $cur ) )
    [[ $COMPREPLY == *: ]] && compopt -o nospace
}

complete -o default -F _mstsc mstsc mstsc.exe

