#!/usr/bin/env sh

_ndisasm()
{
    local cur prev words cword options
    _init_completion
    cur=$(printf '%q' "${cur,,}")

    if [[ $cword -eq 1 ]]; then
        options='-a -i -v -u -b -h -r -e -k -p -o -s'
        COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
        return
    fi

    case $prev in

        -b|-o|-s|-e|-k)
            return
            ;;

        -p)
            options='intel amd cyrix idt'
            ;;

        *)
            options=('-a' '-i' '-u' '-b' '-e' '-k' '-p' '-o' '-s')
            options=$(_compliment words[@]::cword options[@])
            ;; 

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _ndisasm ndisasm ndisasm.exe

