#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_nm()
{
    local cur prev words cword options cmds
    _init_completion
    cur=$(printf '%q' "${cur,,}")
    cmds=( ${words[@]::cword} ) 
    options=( '--debug-syms' '--defined-only' '--demangle' \
        '--demangle=' '--dynamic' '--extern-only' '--format=' \
        '--format=' '--help' '--line-numbers' '--no-demangle' \
        '--no-sort' '--numeric-sort' '--plugin' '--portability' \
        '--print-armap' '--print-file-name' '--print-size' '--radix=' \
        '--reverse-sort' '--size-sort' '--special-syms' '--synthetic' \
        '--target=' '--undefined-only' '--version' '-A' '-B' '-C' '-D' \
        '-P' '-S' '-V' '-X' '-a' '-f' '-g' '-h' '-l' '-n' '-o' '-p' \
        '-r' '-s' '-t' '-u' '-v')
    options=$(_complement cmds[@] options[@])
    COMPREPLY=( $( compgen -f -W '$options' -- $cur ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

complete -o default -F _nm nm

