#!/usr/bin/env sh

_plmdebug_debuggers()
{
    local IFS=$'\n'
    local options=$(where windbg cdb kd nstd 2> /dev/null | sed 's/\r//g')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_plmdebug_pkgs()
{
    # TODO: make this work and test (requires win10)
    local IFS=$'\n'
    local options=$(plmdebug /query 2> /dev/null | sed -e 's/\r//g; /full name/!d; s/.*: //g')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_plmdebug()
{
    local words prev cword
    _init_completion
    local cur=$(printf '%q' "${cur,,}")
    local first_opts=( '/query' \
        '/enabledebug' \
        '/terminate' \
        '/forceterminate' \
        '/cleanterminate' \
        '/suspend' \
        '/resume' \
        '/disabledebug' \
        '/enumeratebgtasks' \
        '/activatebgtasktaskid' \
        '/help' \
        '/?' \
        )
    local terminal_opts=( '/help' '/?' )

    for option in ${terminal_opts[@]} ; do
        if [[ $option == $prev ]]; then
            return
        fi
    done

    if [[ $cword -eq 1 ]]; then
        COMPREPLY=( $(compgen -W '${first_opts[@]}' -- $cur ) )
        return
    fi

    case "${words[1],,}" in
        /query|/terminate|/forceterminate|/cleanterminate|/suspend|/resume|/disabledebug|/enumeratebgtasks)
            if [[ $cword -eq 2 ]]; then
                local IFS=$'\n'
                options=$(_plmdebug_pkgs)
            fi
            ;;

        /enabledebug)
            if [[ $cword -eq 2 ]]; then
                local IFS=$'\n'
                options=$(_plmdebug_pkgs)
            elif [[ $cword -eq 3 ]]; then
                local IFS=$'\n'
                options=$(_plmdebug_debuggers)
            fi
            ;;
    esac

    COMPREPLY=( $(compgen -W '$options' -- $cur ) )
}

complete -o default -F _plmdebug plmdebug plmdebug.exe
