#!/usr/bin/env sh

_regsvr32()
{
    local cur prev words cword
    _init_completion
    cur=$(printf '%q' "$cur")
    COMPREPLY=( $(compgen -W '/u /s /n /i' -- "$cur" ) )
}

complete -o default -F _regsvr32 regsvr32 regsvr32.exe

