#!/usr/bin/env sh

_runas()
{
    local cur prev words cword options cmds
    _init_completion

    case $cur in

        /user\\:*)
            # TODO: list available users
            options=''
            ;;

        /trustlevel\\:*)
            # TODO: list available trust levels
            options=''
            ;;

        *)
            # TODO: cull mutually exclusive options
            cmds=( ${words[@]::cword} ) 
            options=('/noprofile' '/profile' '/env' '/savecred' '/netonly'
            '/user\:' '/showtrustlevels' '/smartcard' '/trustlevel\:')
            options=$(_complement cmds[@] options[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    [[ $COMPREPLY == *: ]] && compopt -o nospace
}

complete -o default -F _runas runas runas.exe

