#!/usr/bin/env sh

_runas()
{
    local cur prev words cword
    _init_completion

    case $cur in

        /user\\:*)
            # TODO: list available users
            options=''
            ;;

        /trustlevel\\:*)
            # TODO: list available trust levels
            options=''
            ;;

        *)
            # TODO: cull duplicate and mutually exclusive options
            options='/noprofile /profile /env /savecred /netonly /user\:
            /showtrustlevels /smartcard /trustlevel\:'
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    [[ $COMPREPLY == *: ]] && compopt -o nospace
}

complete -o default -F _runas runas runas.exe

