#!/usr/bin/env sh

_scm_services()
{
    local services=$(wmic service get name | sed -e '1d' -e '$d' -e 's/\r//' -e 's/ \+$//')
    local IFS=$'\n'
    services=$(printf '%q\n' $services)
    services=`echo "$services" | sed 's/[:=]/\\\&/g'`
    services=${services,,}
    echo "$services"
}

_servicecontrolmanager()
{
    COMPREPLY=()

    local cur=$(printf '%q' "${COMP_WORDS[$COMP_CWORD]}")
    local prev=${COMP_WORDS[$COMP_CWORD-1]}
    local options=''

    # TODO: add more completion options

    if [[ $COMP_CWORD -eq 1 ]] ; then
        options='query queryex start pause interrogate continue stop \
            config description failure failureflag sidtype privs qc \
            qdescription qfailure qfailureflag qsidtype qprivs qtriggerinfo \
            qpreferrednode delete create control sdshow sdset showsid \
            triggerinfo preferrednode getdisplayname getkeyname enumdepend /?'

    elif [[ $COMP_CWORD -eq 2 ]] ; then

        # Command-specific arguments
        case "$prev" in

            query)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            queryex)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            start)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            pause)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            interrogate)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            continue)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            stop)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            config)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            description)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            failure)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            failureflag)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            sidtype)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            privs)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qc)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qdescription)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qfailure)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qfailureflag)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qsidtype)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qprivs)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qtriggerinfo)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            qpreferrednode)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            delete)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            create)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            control)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            sdshow)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            sdset)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            showsid)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            triggerinfo)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            preferrednode)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            getdisplayname)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            getkeyname)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

            enumdepend)
                local IFS=$'\n'
                options=`_scm_services`
                ;;

        esac

    fi

    if [ -n "$options" -a -z "$COMPREPLY" ]; then
        COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
    fi

    return 0
}

complete -o default -F _servicecontrolmanager sc sc.exe

