#!/usr/bin/env sh

_schtasks_users()
{
    local IFS options
    IFS=$'\n'
    options=$(wmic useraccount get name | sed -e '1d' -e 's/\r//' -e 's/ \+$//' -e '/\$$/ d' -e '/^$/ d')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\\&/g -e "/''/d"'
}

_get_schtasks()
{
    local IFS options
    IFS=$'\n'
    options=$(schtasks /query /fo list | sed -e '/^Task/ !d' -e 's/^[^ ]\+ \+//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\\&/g' -e "/''/d"
}

_schtasks()
{
    local cur prev words cword options IFS
    _init_completion
    cur=$(printf '%q' "$cur")

    if [[ $cword -eq 1 ]] ; then
        COMPREPLY=( $( compgen -W '/run /end /create /delete /query /change
        /showsid' -- "${cur,,}" ) )
        return
    fi

    if [[ "$prev" == "/?" ]]; then
        return
    fi

    # Command-specific arguments
    case ${words[1]} in

        /run)

            case "$prev" in
                /s|/p)
                    return
                    ;;

                /u)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/s' '/u' '/p' '/i' '/tn' '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;

        /end)

            case "$prev" in
                /s|/p)
                    return
                    ;;

                /u)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/s' '/u' '/p' '/tn' '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;

        /create)

            case "$prev" in
                /s|/rp|/delay|/rl|/ed|/sd|/du|/et|/ri|/st|/tr|/i|/m|/d|/mo|/p)
                    return
                    ;;

                /sc)
                    options='minute hourly daily weekly monthly once \
                        onstart onlogon onidle onevent'
                    ;;

                /ru|/u)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/s' '/u' '/p' '/tn' '/ru' '/sc'
                    '/mo' '/d' '/m' '/i' '/ec' '/rp' '/tr' '/st' '/ri'
                    '/et' '/du' '/k' '/sd' '/ed' '/it' '/np' '/xml'
                    '/v1' '/f' '/rl' '/z' '/delay' '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;


        /delete)

            case "$prev" in
                /s|/p)
                    return
                    ;;

                /u)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/s' '/u' '/p' '/f' '/tn' '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;

        /query)

            case "$prev" in
                /s|/p)
                    return
                    ;;

                /u)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /xml)
                    options='one'
                    ;;

                /fo)
                    options='table list csv'
                    ;;

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/s' '/u' '/p' '/fo' '/xml' '/nh' '/v' '/tn' '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;

        /change)

            case "$prev" in
                /s|/rp|/delay|/rl|/ed|/sd|/ec|/du|/et|/ri|/st|/tr|/xml|/p)
                    return
                    ;;

                /u)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /ru)
                    IFS=$'\n'
                    options=$(_schtasks_users)
                    ;;

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/s' '/u' '/p' '/tn' '/ru' '/rp'
                    '/tr' '/st' '/ri' '/et' '/du' '/k' '/sd' '/ed'
                    '/it' '/rl' '/enable' '/disable' '/z' '/delay'
                    '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;

        /showsid)

            case "$prev" in

                /tn)
                    IFS=$'\n'
                    options=$(_get_schtasks)
                    ;;

                *)
                    options=('/tn' '/hresult')
                    options=$(_compliment words[@]::cword options[@])
                    ;;

            esac
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "${cur,,}" ) )
}

complete -o default -F _schtasks schtasks schtasks.exe

