#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_sed()
{
    local cur prev words cword options cmds
    _init_completion

    cur=$(printf '%q' "${cur,,}")
    cmds=( ${words[@]::cword} ) 

    options=( '-n' '--quiet' '--silent' '-e' '--expression=' '-f' \
        '--file=' '--follow-symlinks' '-i' '--in-place' '--in-place=' '-b' \
        '--binary' '-l' '--line-length=' '--posix' '-r' '--regexp-extended' '-s' \
        '--separate' '-u' '--unbuffered' '-z' '--null-data' '--help' '--version' )
    options=$(_complement cmds[@] options[@])

    COMPREPLY=( $( compgen -f -W '$options' -- $cur ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

complete -o default -F _sed sed

