#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_sed()
{
	COMPREPLY=()

    local cur=$(printf '%q' "${COMP_WORDS[COMP_CWORD]}")
    local options=''
    local option_list=( '-n' '--quiet' '--silent' '-e' '--expression=' '-f' \
        '--file=' '--follow-symlinks' '-i' '--in-place' '--in-place=' '-b' \
        '--binary' '-l' '--line-length=' '--posix' '-r' '--regexp-extended' '-s' \
        '--separate' '-u' '--unbuffered' '-z' '--null-data' '--help' '--version' )

    if [[ $cur == *= ]]; then
        compopt -o nospace
    fi

    for option in ${option_list[@]} ; do
        local found=0

        for word in ${COMP_WORDS[@]::${COMP_CWORD}} ; do
            if [[ $word == $option ]]; then
               found=1 
               break
            fi
        done

        if [[ $found -eq 0 ]]; then
            options+="$option "
        fi
    done

    COMPREPLY=( $( compgen -f -W "$options" -- $cur ) )

	return 0
}

complete -o default -F _sed sed

