#!/usr/bin/env sh

# TODO: remove recommendations immediately after switches that take parameters
# TODO: handle mutually exclusive options, long and short form options that are equivalent
# TODO: see _split_longopt

_tail()
{
    local cur prev words cword options cmds
    _init_completion

    cur=$(printf '%q' "${cur,,}")
    cmds=( ${words[@]::cword} ) 

    options=( '--bytes=' '--follow' '--follow=' '--help' '--lines=' \
        '--max-unchanged-stats=' '--pid=' '--quiet' '--retry' '--silent' \
        '--sleep-interval=' '--verbose' '-F' '-c' '-f' '-n' '-q' '-s' '-v' )
    options=$(_complement cmds[@] options[@])

    COMPREPLY=( $( compgen -f -W '$options' -- $cur ) )
    [[ $COMPREPLY == *= ]] && compopt -o nospace
}

complete -o default -F _tail tail tail.exe

