#!/usr/bin/env sh

_windows_tasklist()
{
	COMPREPLY=()

    local cur=$(printf '%q' "${COMP_WORDS[COMP_CWORD]}")
    local options=''
	local prev=${COMP_WORDS[COMP_CWORD-1]}

    if [[ $prev == "/?" ]]; then
		COMPREPLY=( $( compgen -W "" -- $cur ) )

	else
        options='/apps /v /fi /nh /fo /svc /m /p /s /u /?'

        # Command-specific arguments
        case "$prev" in

            /s)
                options=''
                ;;

            /u)
                options=''
                ;;

            /p)
                options=''
                ;;

            /m)
                options=''
                ;;

            /fi)
                # TODO: tons of options here
                options=''
                ;;

            /fo)
                options='table list csv'
                ;;

        esac

        if [ -n "$options" -a -z "$COMPREPLY" ]; then
            COMPREPLY=( $(compgen -W '${options}' -- ${cur} ) )
        fi
    fi

	return 0
}

complete -o default -F _windows_tasklist tasklist tasklist.exe

