#!/usr/bin/env sh

# TODO: mutual exclusivity and dependence of options

_tasklist_computer_names()
{
    local IFS options
    IFS=$'\n'
    local options=$(net view /all 2> /dev/null | sed -e '/^\\\\/!d' -e 's/ .*//' -e 's/^\\\\//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_tasklist_users()
{
    local IFS options
    IFS=$'\n'
    options=$(wmic useraccount get name 2> /dev/null | sed -e '1d' -e '$d' -e 's/\W*$//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_tasklist()
{
    local cur prev words cword options IFS
    _init_completion

    cur=$(printf '%q' "${cur,,}")

    # Command-specific arguments
    case $prev in

        /s)
            IFS=$'\n'
            options=$(_tasklist_computer_names)
            ;;

        /u)
            IFS=$'\n'
            options=$(_tasklist_users)
            ;;

        /m|/p|'/?')
            return
            ;;

        /fi)
            # TODO: tons of options here
            return
            ;;

        /fo)
            options='table list csv'
            ;;

        *)
            local cmds=( ${words[@]::cword} )
            options=('/apps' '/v' '/fi' '/nh' '/fo' '/svc' '/m' '/p' '/s' '/u' '/?')
            options=$(_complement cmds[@] options[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _tasklist tasklist tasklist.exe

