#!/usr/bin/env sh

_windows_tasklist()
{
    local cur prev words cword options
    _init_completion

    cur=$(printf '%q' "${cur,,}")

    if [[ $prev == "/?" ]]; then
        return
    fi

    # Command-specific arguments
    case $prev in

        /s)
            # TODO: suggest computer names
            options=''
            ;;

        /u)
            # TODO: suggest users
            options=''
            ;;

        /p)
            options=''
            ;;

        /m)
            options=''
            ;;

        /fi)
            # TODO: tons of options here
            options=''
            ;;

        /fo)
            options='table list csv'
            ;;

        *)
            options='/apps /v /fi /nh /fo /svc /m /p /s /u /?'
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _windows_tasklist tasklist tasklist.exe

