#!/usr/bin/env sh

_taskkill_task_images()
{
    local options IFS
    IFS=$'\n'
    options=$(tasklist /fo list | sed -e '/^Image/ !d' -e 's/^Image Name: \+//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\\&/g' -e "/''/d"
}

_taskkill()
{
    local cur prev words cword options IFS
    _init_completion
    cur=$(printf '%q' "${cur,,}")

    if [[ $prev == "/?" ]]; then
        return
    fi

    # Command-specific arguments
    case $prev in

        /s)
            return
            ;;

        /u)
            return
            ;;

        /p)
            return
            ;;

        /fi)
            # TODO: lots of options here...
            return
            ;;

        /pid)
            _pids
            return
            ;;

        /im)
            options=$(_taskkill_task_images)
            ;;

        *)
            local cmds=( ${words[@]::cword} )
            options=('/f' '/t' '/im' '/pid' '/fi' '/p' '/s' '/u')
            options=$(_complement cmds[@] options[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- "$cur" ) )
}

complete -o default -F _taskkill taskkill taskkill.exe

