#!/usr/bin/env sh

_wevtutil()
{
	COMPREPLY=()

    local cur=$(printf '%q' "${COMP_WORDS[COMP_CWORD]}")
    local prev=${COMP_WORDS[COMP_CWORD-1]}
    local options=''

    if [[ $COMP_CWORD -eq 1 ]]; then
        local commands='enum-logs get-log set-log \
            enum-publishers get-publisher \
            install-manifest uninstall-manifest \
            query-events get-log-info export-log \
            archive-log clear-log /?'

        COMPREPLY=( $( compgen -W "$commands" -- $cur ) )

    elif [[ $prev == '/?' ]]; then
        return 0

    elif [[ $cur == '/?' ]]; then
        return 0

    else
        local command=${COMP_WORDS[1]}

        case "$command" in

            al)
                ;&
            archive-log)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    options=''
                else
                    compopt -o nospace
                    options='/locale:'
                fi
                ;;

            cl)
                ;&
            clear-log)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    local IFS=$'\n'
                    options=`wevtutil el`
                    options=${options// /\\\ }
                    options=${options///}
                else
                    compopt -o nospace
                    options='/backup:'
                fi
                ;;

            um)
                ;&
            uninstall-manifest)
                ;&
            el)
                ;&
            enum-logs)
                ;&
            ep)
                ;&
            enum-publishers)
                options=''
                ;;

            epl)
                ;&
            export-log)
                if [[ ${COMP_CWORD} -le 3 ]]; then
                    options=''
                else
                    options='/logfile:true /logfile:false \
                        /structuredquery:true \
                        /structuredquery:false /query: \
                        /overwrite:true /overwrite:false' 
                fi
                ;;

            gl)
                ;&
            get-log)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    options=''
                else
                    options='/format:xml /format:text' 
                fi
                ;;

            gp)
                ;&
            get-publisher)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    local IFS=$'\n'
                    options=`wevtutil ep`
                    options=${options// /\\\ }
                    options=${options///}
                else
                    options='/getevents:true /getevents:false \
                        /getmessage:true /getmessage:false /format:xml \
                        /format:text' 
                fi
                ;;

            im)
                ;&
            install-manifest)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    options=''
                else
                    options='/resourceFilePath: /messageFilePath: \
                        /parameterFilePath:' 
                fi
                ;;

            qe)
                ;&
            query-events)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    options=''
                else
                    options='/logfile:true /logfile:false \
                        /structuredquery:true /structuredquery:false /query: \
                        /bookmark: /savebookmark: /reversedirection:true \
                        /reversedirection:false /format:xml /format:text \
                        /format:renderedxml /locale: /count: /element:' 
                fi
                ;;

            sl)
                ;&
            set-log)
                if [[ ${COMP_CWORD} -eq 2 ]]; then
                    options=''
                else
                    options='/enabled:true /enabled:false /quiet:true \
                        /quiet:false /filemax: /isolation:system \
                        /isolation:application /isolation:custom \
                        /logfilename: /retention:true /retention:false \
                        /autobackup:true /autobackup:false /maxsize: \
                        /level: /keywords: /config:'
                fi
                ;;

        esac

        COMPREPLY=( $( compgen -W '${options}' -- ${cur} ) )

    fi

	return 0
}

complete -o default -F _wevtutil wevtutil wevtutil.exe

