#!/usr/bin/env sh

# TODO: implement mutual exclusivity and ordering
# TODO: start pushing common functions down

_windbg_services()
{
    local IFS options
    IFS=$'\n'
    options=$(sc query | sed -e '/^SERV/!d' -e 's/^[^ ]\+ //')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_windbg_task_images()
{
    local IFS options
    IFS=$'\n'
    options=$(tasklist /fo list | sed -e '/^Image/ !d' -e 's/^[^:]\+: \+//')
    printf '%q\n' ${options,,} | sed -e 's/[:=]/\\&/g' -e "/''/d"
}

_windbg()
{
    local cur prev words cword options IFS found terminal_options first_options options_list
    _init_completion
    cur=$(printf '%q' "$cur")

    terminal_options=( '-IA ' '-IAS' '-IU' '-I' '-IS' '-?' )
    first_options=( '-server' '-remote' )
    first_options+=( ${terminal_options[@]} )

    # TODO: lsrcpath should only follow "-remote"

    options_list=( '-lsrcpath' '-premote' '-ee' '-clines' '-d'
        '-a' '-e' '-failinc' '-g' '-G' '-hd' '-j' '-n' '-noshell' '-o'
        '-Q' '-QY' '-QS' '-QSY' '-robp' '-secure' '-ses' '-sdce' '-sicv'
        '-sins' '-snc' '-snul' '-sup' '-sflags' '-T' '-v' '-log' '-logo'
        '-loga' '-noinh' '-i' '-y' '-srcpath' '-k' '-kl' '-kx' '-c' '-pb' '-pd'
        '-pe' '-pr' '-pt' '-pv' '-W' '-WF' '-WX' '-zp' '-p' '-pn' '-psn' '-z' )

	if [[ $cword -eq 1 ]] ; then
        COMPREPLY=( $( compgen -W "${options_list[*]} ${first_options[*]}" -- $cur ) )
        [[ $COMPREPLY == -a* ]] && compopt -o nospace
        return
    fi

    for option in ${terminal_options[@]} ; do
        if [[ $option == ${words[1]} ]]; then
            return
        fi
    done

    # Command-specific arguments
    case $prev in

        -a*)
            # TODO: list dlls 
            options=''
            ;;

        -sflags)
            # TODO: ' 0x'
            options=''
            ;;

        -p)
            _pids
            return
            ;;

        -pn)
            IFS=$'\n'
            options=$(_windbg_task_images)
            ;;

        -psn)
            IFS=$'\n'
            options=$(_windbg_services)
            ;;

        -ee)
            options='masm c++'
            ;;

        -remote|-premote|-server|-k|-e|-clines|-T|-log|-logo|-loga|-i|-y|-srcpath|-kx|-c|-pt|-W|-WF|-zp|-z)
            return
            ;;

        *)
            local cmds=( ${words[@]::cword} ) 
            options=$(_complement cmds[@] options_list[@])
            ;;

    esac

    COMPREPLY=( $(compgen -W '$options' -- $cur ) )
    [[ $COMPREPLY == -a* ]] && compopt -o nospace
}

complete -o default -F _windbg windbg windbg.exe

